
include { CCDSFilter } from './modules/local/CCDSFilter'
include { CSN } from './modules/local/CSN'
include { Carol } from './modules/local/Carol'
include { Downstream } from '.modules/local/Downstream'
include { Draw } from '.modules/local/Draw'
include { GXA } from '.modules/local/GXA'
include { LOVD } from '.modules/local/LOVD'
include { NMD } from '.modules/local/NMD'
include { NearestGene } from '.modules/local/NearestGene'
include { AncestralAllele } from '.modules/local/AncestralAllele'
include { makeHeader } from '.modules/local/makeHeader'
inclide { CompileVCF } from '.modules/local/CompileVCF'
